version: '3.1'

services:
  db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: matee
      POSTGRES_DB: mav
    ports:
      - '5555:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scraper-network
  scraper:
    build:
      context: ./
    restart: always
    depends_on:
      - db
    environment:
      DB_PASSWORD: "$POSTGRES_PASSWORD"
      DB_USERNAME: matee
      DB_DB: mav
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - scraper-network

networks:
  scraper-network:

volumes:
  pgdata:
